import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#fff', paddingTop: 16 },
  centered: { alignItems: 'center', justifyContent: 'center', gap: 8 },
  form: { paddingHorizontal: 16, gap: 8 },
  modal: { flex: 1, padding: 24, gap: 12, backgroundColor: '#fff' },
  title: { fontSize: 24, fontWeight: '700', marginBottom: 4 },
  sectionTitle: { fontSize: 13, fontWeight: '700', color: '#71717a', marginTop: 8 },
  input: {
    borderWidth: 1,
    borderColor: '#d4d4d8',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 16,
  },
  multiline: { minHeight: 72, textAlignVertical: 'top' },
  button: {
    backgroundColor: '#2563eb',
    borderRadius: 8,
    paddingVertical: 12,
    alignItems: 'center',
  },
  syncButton: { backgroundColor: '#0f766e' },
  secondaryButton: { backgroundColor: '#f4f4f5' },
  secondaryLabel: { color: '#3f3f46', fontSize: 16, fontWeight: '600' },
  buttonDisabled: { opacity: 0.5 },
  buttonLabel: { color: '#fff', fontSize: 16, fontWeight: '600' },
  syncSummary: { fontSize: 12, color: '#52525b' },
  syncError: { fontSize: 12, color: '#b91c1c' },
  listContent: { padding: 16, gap: 12 },
  listHeader: { fontSize: 13, fontWeight: '600', color: '#71717a' },
  row: {
    borderWidth: 1,
    borderColor: '#e4e4e7',
    borderRadius: 8,
    padding: 12,
    gap: 4,
  },
  rowName: { fontSize: 16, fontWeight: '600' },
  rowNotes: { fontSize: 14, color: '#3f3f46' },
  rowMeta: { fontSize: 12, color: '#a1a1aa', fontVariant: ['tabular-nums'] },
  muted: { color: '#71717a' },
  errorTitle: { fontSize: 18, fontWeight: '700' },
  errorBody: { color: '#b91c1c', textAlign: 'center', paddingHorizontal: 24 },

  // follow-ups
  checkbox: {
    width: 26,
    height: 26,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: '#a1a1aa',
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxDone: { backgroundColor: '#0f766e', borderColor: '#0f766e' },
  checkboxMark: { color: '#fff', fontWeight: '800' },
  followUpRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  followUpTitle: { fontSize: 16, flexShrink: 1 },
  followUpDone: { textDecorationLine: 'line-through', color: '#a1a1aa' },

  // sync inspector
  statRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 4 },
  statLabel: { color: '#52525b', fontSize: 14 },
  statValue: { fontWeight: '700', fontSize: 14, fontVariant: ['tabular-nums'] },
  flagged: {
    borderWidth: 1,
    borderColor: '#fca5a5',
    backgroundColor: '#fef2f2',
    borderRadius: 8,
    padding: 12,
    gap: 4,
  },
  flaggedTitle: { fontWeight: '700', color: '#b91c1c' },
  flaggedBody: { fontSize: 13, color: '#7f1d1d' },
});
